execute if entity @s[hasitem={item=blade:sample,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade sample
execute if entity @s[hasitem={item=blade:slashblade,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade slashblade
execute if entity @s[hasitem={item=blade:wood,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade wood
execute if entity @s[hasitem={item=blade:bamboo,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade bamboo
execute if entity @s[hasitem={item=blade:silverbanboo,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade silverbanboo
execute if entity @s[hasitem={item=blade:white,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade white
execute if entity @s[hasitem={item=blade:slashblade_named,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade slashblade_named
execute if entity @s[hasitem={item=blade:wooden_katana,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade wooden_katana
execute if entity @s[hasitem={item=blade:stone_katana,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade stone_katana
execute if entity @s[hasitem={item=blade:iron_katana,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade iron_katana
execute if entity @s[hasitem={item=blade:diamond_katana,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade diamond_katana
execute if entity @s[hasitem={item=blade:golden_katana,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade golden_katana
execute if entity @s[hasitem={item=blade:tagayasan,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade tagayasan
execute if entity @s[hasitem={item=blade:yamato,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade yamato
execute if entity @s[hasitem={item=blade:yuzukitukumo,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade yuzukitukumo
execute if entity @s[hasitem={item=blade:agito,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade agito
execute if entity @s[hasitem={item=blade:agito_rust,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade agito_rust
execute if entity @s[hasitem={item=blade:orotiagito,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade orotiagito
execute if entity @s[hasitem={item=blade:sange,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade sange
execute if entity @s[hasitem={item=blade:yasha,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade yasha
execute if entity @s[hasitem={item=blade:fox_white,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade fox_white
execute if entity @s[hasitem={item=blade:fox_black,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade fox_black
execute if entity @s[hasitem={item=blade:muramasa,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade muramasa
execute if entity @s[hasitem={item=blade:sabigatana,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade sabigatana
execute if entity @s[hasitem={item=blade:doutanuki,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade doutanuki
execute if entity @s[hasitem={item=blade:nihil,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade nihil
execute if entity @s[hasitem={item=blade:nihilex,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade nihilex
execute if entity @s[hasitem={item=blade:crimsoncherry,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade crimsoncherry
execute if entity @s[hasitem={item=blade:nihilbx,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade nihilbx
execute if entity @s[hasitem={item=blade:nihilul,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade nihilul
execute if entity @s[hasitem={item=blade:snowcrow,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade snowcrow
execute if entity @s[hasitem={item=blade:darkraven,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade darkraven
execute if entity @s[hasitem={item=blade:toyako,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade toyako
execute if entity @s[hasitem={item=blade:fluorescentbar,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade fluorescentbar
execute if entity @s[hasitem={item=blade:yukari,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade yukari
execute if entity @s[hasitem={item=blade:kamuy_fire,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade kamuy_fire
execute if entity @s[hasitem={item=blade:kamuy_lightning,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade kamuy_lightning
execute if entity @s[hasitem={item=blade:kamuy_water,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade kamuy_water
execute if entity @s[hasitem={item=blade:kamuy_none,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade kamuy_none
execute if entity @s[hasitem={item=blade:frosty_cherry,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade frosty_cherry
execute if entity @s[hasitem={item=blade:moonlightcherry,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade moonlightcherry
execute if entity @s[hasitem={item=blade:greenmist,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade greenmist
execute if entity @s[hasitem={item=blade:aquablaze,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade aquablaze
execute if entity @s[hasitem={item=blade:blue,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade blue
execute if entity @s[hasitem={item=blade:katana_red,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade katana_red
execute if entity @s[hasitem={item=blade:tachi,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade tachi
execute if entity @s[hasitem={item=blade:katana,location=slot.weapon.mainhand}] run scriptevent zex:haveBlade katana
